yolo_model:

  config_file:
    name: autorally.cfg
  weight_file:
    name: autorally_4000.weights
  threshold:
    value: 0.15
  detection_classes:
    names:
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - car
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
