yolo_model:

  config_file:
    name: yolo-voc.cfg
  weight_file:
    name: yolo-voc.weights
  threshold:
    value: 0.25
  detection_classes:
    names:
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - car
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
      - ignore
